name: CI/CD Inicial

on: [push]

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Testar workflow
        run: echo "Workflow funcionando"